### ISSUE TITLE
SiteSpeedSampleRate Config in the Backend

### ISSUE THREAD

**Issue by andreasemer** [fooman/googleanalyticsplus#100]
Do you guys think it makes sense to give the backend user the option to set the SiteSpeedSampleRate?  https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference

I could create a PR for this, if you think people will use it.

**Comment by fooman** [comment]
I've had one request for it - to me it seems just as easy to put it into the template file in your theme directly. If you like to contribute it, happy to merge it in.
