### ISSUE TITLE
allowLinker option

### ISSUE THREAD

**Issue by cmaysles** [fooman/googleanalyticsplus#102]
In some cases we need to add the following param to the ga(create) line and it would be great if you could add an additional parameter to the configuration to allow this: {'allowLinker': true});

ga('create', 'UA-XXXXXX', 'auto', {'allowLinker': true});

**Comment by andreasemer** [comment]
I have add this feature for you here https://github.com/fooman/googleanalyticsplus/pull/104/commits/20c8d03274e3e172dfc626ebe6b44f2bc6415008 

Merry Christmas :-)

**Comment by cmaysles** [comment]
Thanks. Keep up the great work!

**Comment by andreasemer** [comment]
@fooman @cmaysles This issue is resolved, the code is merged, can you please close this ticket?
