### ISSUE TITLE
Advanced Parameters

### ISSUE THREAD

**Issue by cmaysles** [fooman/googleanalyticsplus#103]
With so many additional ways to configure GA, having an advance parameters textarea box in the config would make this plugin much more flexible.  If you could add a simple text area box in the config that just echoes it into the GA output, this will take care of a lot of the advanced configurations. Example, I need to insert the following, but cannot do it without hacking code or setting up an override:

ga('require', 'linker'); 
ga('linker:autoLink', ['domain1.com', 'domain2.com'] );

**Comment by fooman** [comment]
@cmaysles I'd like to keep this as straight forward as possible for entry level users so am currently not convinced on the idea of allowing an advanced input box.

It is very straight forward to customise the template file https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/template/fooman/googleanalyticsplus/universal.phtml for your purposes.

**Comment by cmaysles** [comment]
I agree, keeping it easy to use is a must. That's why I was suggesting just having a single "advanced" box that would allow for expert use as well. Novice users will most likely just ignore that box. Using the template overrides is doable, but not really ideal for the reason that the configurations will be split between the extension configuration section in the admin, and within the phtml file.  From a management perspective, it would be better to keep it all in one place.
