### ISSUE TITLE
New Google Tag Manager Implementation Method

### ISSUE THREAD

**Issue by Morgy93** [fooman/googleanalyticsplus#105]
Google Tag Manager changed its implementation method: https://developers.google.com/tag-manager/quickstart

You now need to place the gtm container script as close to the opening <head> tag as possible.
And the <noscript> snippet immediately after the opening <body> tag.

**Comment by shaan-19** [comment]
As mentioned in https://github.com/fooman/googleanalyticsplus/issues/65

Please move the <script> to the top of the <head> tag and the <noscript> snippet to the top of the <body> tag.

**Comment by shaan-19** [comment]
@fooman any update for this issue?

**Comment by fooman** [comment]
@shaan-19 Updates to our Magento 1 extensions are currently not high on our list of our priorities. You can try shifting these lines 

            <block type="googleanalyticsplus/tagManager" name="googleanalyticsplus_tagmanager"
                   as="googleanalyticsplus_tagmanager"/>

from here https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/layout/googleanalyticsplus.xml#L18 to
here https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/layout/googleanalyticsplus.xml#L11

**Comment by fooman** [comment]
I have just merged a pull request #115 which moves the JS into the html head. Please note that you would need to remove the previously copied snippet and just enter your GTM id.
