### ISSUE TITLE
Configuring Custom Dimensions

### ISSUE THREAD

**Issue by JoshuaEstes** [fooman/googleanalyticsplus#107]
First off, this is a damn good extension. This is used on a lot of stores and this is the go to extension. Thanks for all your hard work on this.

https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

Currently we have a need to track Customer Group (along with User ID which is supported) as a Custom Dimension on a few of our sites. I thought it might be a nice feature to have a configuration setting for tracking Customer Groups (or other data) via customer dimensions.

BTW I'd be happy to offer up a PR for this feature if you'd like

**Comment by fooman** [comment]
Hi @JoshuaEstes thanks for the feedback - much appreciated.

I currently don't anticipate me being able to put time into feature development for Magento 1 extensions these days, it's all focussed on M2 right now. 

So please go ahead creating a PR for it and I will merge it in.

**Comment by JoshuaEstes** [comment]
PR #110
