### ISSUE TITLE
product page price does not include tax

### ISSUE THREAD

**Issue by phoenix164** [fooman/googleanalyticsplus#109]
The code in Remarketing.php below outputs price excluding tax. Any ideas how to change this to output price including tax?

public function getEcommPValue()
    {
        if ($this->getPageType() == self::GA_PAGETYPE_PRODUCT) {
            return sprintf(
                "%01.2f", Mage::helper('googleanalyticsplus')->convert(
                    Mage::registry('current_product'),
                    'final_price',
                    Mage::app()->getStore()->getCurrentCurrencyCode()

**Comment by fooman** [comment]
@phoenix164 you'll probably need to take a look at using
`Mage_Tax_Helper_Data::getPrice()`
