### ISSUE TITLE
No Analytics code after enabling extension

### ISSUE THREAD

**Issue by gputignano** [fooman/googleanalyticsplus#113]
On Magento v1.9.3.4 after installing and enabling this extension I can't see any tracking code in HTML page.
I set:
Enabled: Yes
Account Number: UA-XXXXXXXX-1

**Comment by fooman** [comment]
I am currently not able to reproduce this. Please make sure to enable it in the right section of the settings (Google Universal Analytics by Fooman). If the issue persists with the latest version please open a new report.
