### ISSUE TITLE
Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by Whizzzer** [fooman/googleanalyticsplus#116]
I tried to install this plugin (plus the common one) via modman, but after clearing the cache it gave an error 500 on the webpage.

With some debugging enabled, it shows:

> Fatal error: Can't use method return value in write context in /path/to/magento-site/includes/src/Fooman_GoogleAnalyticsPlus_Block_Universal.php on line 239

Which then should be [this](https://github.com/fooman/googleanalyticsplus/blob/373b1bf56ad7b9360e71c51f760a3fce30a15426/app/code/community/Fooman/GoogleAnalyticsPlus/Block/Universal.php#L239)??

Disabling the module via app/etc/modules/Fooman_GoogleAnalyticsPlus.xml (and refreshing the cache) makes the website working again, yet without the plugin.

What am I doing wrong?

O, I'm running Magento 1.9.3.7..

**Comment by fooman** [comment]
It looks like you are using Magento's compilation mode. Please disable this before installing the extension and Rerun the compilation mode after finishing the installation.

**Comment by fooman** [comment]
Actually what version of php do you currently use?

Can you try changing

        return (
            Mage::getStoreConfigFlag('google/analyticsplus_optimize/enabled')
            && !empty($this->getGoogleOptimizeContainerId())
        );

to

        $containerId = $this->getGoogleOptimizeContainerId();
        return (
            Mage::getStoreConfigFlag('google/analyticsplus_optimize/enabled')
            && !empty($containerId)
        );

**Comment by Whizzzer** [comment]
During installation compilation mode was disabled (I followed the installation instructions)

I'm using PHP-FPM on CentOS in combination with Apache:
[whizzer@server ~]$ php-fpm -v
PHP 5.4.16 (fpm-fcgi) (built: Nov 15 2017 16:35:28)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
[whizzer@server ~]$ php -v
PHP 5.4.16 (cli) (built: Nov 15 2017 16:33:54)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
[whizzer@server ~]$

Changing the code to the proposed one fixed the issue. Because my coding skills are "horrible", can you explain to me why the change fixed the problem?

**Comment by hostep** [comment]
@Whizzzer, it's a new feature in PHP 5.5 which is being used, the code won't work in PHP 5.4, see this page to see it was only added in PHP 5.5: http://php.net/manual/en/migration55.new-features.php#migration55.new-features.empty
