### ISSUE TITLE
Universal Analytics not saving

### ISSUE THREAD

**Issue by refueledinc** [fooman/googleanalyticsplus#16]
I've installed the latest github repo to a fresh magento 1.8.1 install and can't get the Universal Analytics tracking code to save.

When I enter the tracking code (the entire script provided in GA account) and save, the script is removed from the text field and no Universal Tracking can be found in the frontend source code. I have no issue getting the Classic Analytics working.

Any ideas as to the issue?

**Comment by aqvapex** [comment]
Hi refueledinc,

I got the same problem as you did. Did you fix that?
