### ISSUE TITLE
Troubleshooting the Tracking Code

### ISSUE THREAD

**Issue by davidalexander** [fooman/googleanalyticsplus#35]
Hi Kristof

I'd like to propose a feature where there is an admin config to switch the ga script to the appropriate debug version.

See [Debugging with ga_debug.js](https://developers.google.com/analytics/resources/articles/gaTrackingTroubleshooting#gaDebug) and [Google Analytics Debugging with ga_debug.js](http://davidwalsh.name/google-analytics-debugging)

I know there is a [Chrome Extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) that does this but it's useful to have this across browsers/devices.

**Comment by fooman** [comment]
we just pushed v0.15.15 which has support for enabling the debug script. Let us know how it goes.
