### ISSUE TITLE
adblock software

### ISSUE THREAD

**Issue by sensalot** [fooman/googleanalyticsplus#5]
Changing to the doubleclick Javascript for remarketing reasons, can result in a huge drop of visitors in GA. Adblockers block the Double click scipt but allow GA script.

Please look here http://andrescholten.net/google-analytics-retargeting-for-adwords-and-adblock-software/

Could this be implemented?

**Comment by octobresept** [comment]
FYI, AdBlock no longer blocks the dc.js Google Analytics Tracking Code so I think this issue could be closed.

**Comment by fooman** [comment]
Great to hear - thanks for the feedback. Will close this one for now.
