### ISSUE TITLE
Too much quotes in the Remarketing Tag...

### ISSUE THREAD

**Issue by KoenWijnstok** [fooman/googleanalyticsplus#59]
Yesterday I've implemented remarketing, but the Google Tag manager keeps giving me errors.
It looks like there just are too many quotes around the ecomm_ variables.

In my products source i've got the following:
ecomm_prodid: ''Cavalier-SinterklaasPuur'',

and on the cart page this with 2 items added:
 ecomm_prodid: '['Cavalier-SinterklaasMelk','Cavalier-SinterklaasPuur']',

Please note that the '' is not a " but just 2 '  

I'm currently running the latest version from github.

Error: Value passed as array has misplaced quotes.

Google Tag manager is giving me this info:
Conversion tag parameters
ecomm_prodid	 '['Cavalier-SinterklaasMelk','Cavalier-SinterklaasPuur']'
ecomm_pagetype	 'cart'
ecomm_totalvalue	 '[4.52,4.52]'

**Comment by fooman** [comment]
It looks like you are using an alphanumeric product id - please try with the latest release which should work better. Please re-open this issue if necessary.
