### ISSUE TITLE
appears not to include script on CE 1.8.1

### ISSUE THREAD

**Issue by tofuwarrior** [fooman/googleanalyticsplus#62]
Have installed with composer fine from this repo, admin configuration options show fine but analytics script is not included. Standard magento works and the older fooman classic analytics available from connect works so can't see why this one doesn't. Don't think it is me.

**Comment by rubenCodeforges** [comment]
same for me

**Comment by fooman** [comment]
Do you have the setting `System > Configuration > Developer > Template Settings > Allow Symlinks` enabled? Default composer installs will link the template files. Alternatively you could use a different deploy mode.

Also please confirm which version is installed and verify that all files are present and readable by the server.

**Comment by magnetomedia** [comment]
Hi, this worked out for me thanks. But keeping the symlinks on is stated a not secure way for production .. any idea about it?

**Comment by fooman** [comment]
Please see http://magento.stackexchange.com/questions/35243/are-symlinks-on-templates-a-security-problem-and-if-yes-why

You can also change the deploy method to copy for the Magento-Composer installer if you do not want to use symlinks.
