### ISSUE TITLE
Tag Assistant keeps saying "Conversion label not set." when field is left blank.

### ISSUE THREAD

**Issue by wssweb** [fooman/googleanalyticsplus#63]
The new remarketing tags no longer give you a google_conversion_label. Yet the Tag Assistant keeps saying its missing with the newest version of of googleanalyticsplus. 

This is due to "label=&amp;" being left in the scr=" " of the image tag in the noscript tag when the Conversion Label field is left blank on the back end. When I removed it from /app/design/frontend/base/default/template/fooman/googleanalyticsplus/remarketing.phtml the error went away.

**Comment by fooman** [comment]
I have made some changes so that the label is only used if entered for the noscript. Could you please update (0.16.4) and confirm this is working for you.

**Comment by wssweb** [comment]
It is working, but it outputs now with & instead of `&amp;`
```
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/testid/?value=0&guid=ON&script=0"/>
```
```
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/testid/?value=0&label=testlabel&guid=ON&script=0"/>
```

**Comment by fooman** [comment]
Thanks for the feedback. Using &amp; or just & is fine according to Google - however I will change this back in the future to the more commonly used &amp;.
