### ISSUE TITLE
Paypal tracking

### ISSUE THREAD

**Issue by Mlinnig** [fooman/googleanalyticsplus#64]
First of all, thanks for your effort! I don't know whether is the right way to ask, but just move/delete it in case it is. 

I want to track payments that are being made via PayPal when a costumer is on a rush and does not wait for the PayPal redirect to my onepage/success.html. Is there a way to do this with this extension?

Thanks!

**Comment by fooman** [comment]
Currently the extension utilises the success page to display the tracking code.

Theoretically it is now possible to send tracking information to Google out of band. This is similar to this existing feature request https://github.com/fooman/googleanalyticsplus/issues/32 - so will close this one.
