### ISSUE TITLE
Tag Manager should be placed after opening body tag, not before closing head tag

### ISSUE THREAD

**Issue by peterjaap** [fooman/googleanalyticsplus#65]
> Paste this snippet into your website template page so that it appears immediately after the opening <body> tag.

Source; https://developers.google.com/tag-manager/quickstart

Relevant code; https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/layout/googleanalyticsplus.xml#L11

So the tag manager block should be placed in the after_body_start reference, instead of in the before_head_end reference.

**Comment by fooman** [comment]
Hi Peter, thanks for the feedback. I moved the block in the latest version https://github.com/fooman/googleanalyticsplus/commit/7b0e3cc819cfe01f28c4de7930bccec53e4efbd9#diff-0f5712542952c63f2dc713f8f287b02bL1

**Comment by shaan-19** [comment]
@fooman 

I think this is incorrect, going to the same linked google page (https://developers.google.com/tag-manager/quickstart), it says place the <script> code as close to the opening <head> tag as possible and the <noscript> code immediately after the opening <body> tag. 

Would it be possible to move it back to the head section and/or create a script vs no-script field?

**Comment by fooman** [comment]
@shaan-19 do you mind opening a new issue for this? It's totally possible that Google changed their recommendation yet again.

**Comment by shaan-19** [comment]
Actually I see it is covered in this issue: https://github.com/fooman/googleanalyticsplus/issues/105

My fault, I should have checked first to see if it had been posted.
