### ISSUE TITLE
404 page on configuration left hand menu support link

### ISSUE THREAD

**Issue by SEjoe** [fooman/googleanalyticsplus#68]
Everything else appears to be working, i'm using the latest versions installed via connect, i'm sure the support button is non essential but these kinda things play on my mind a little :)
![supportbutton](https://cloud.githubusercontent.com/assets/11789103/6986744/9bdae9e6-d9fd-11e4-84e6-70592b49c0f8.gif)

**Comment by SEjoe** [comment]
also the displays for addwords are remarkably different to your documentation now.

**Comment by fooman** [comment]
Have you logged out and back in after the installation? That would normally solve the 404. Also check the version you installed is the most recent (0.16.x) as we have recently made some changes (removal of classic) using the most recent documentation (v1.8).

**Comment by SEjoe** [comment]
Hi, Yes i did try to log out and in before posting here. I'm using Fooman_GoogleAnalyticsPlus 0.16.7 (beta)

**Comment by fooman** [comment]
Can you please double check that the Fooman Common extension is also installed.

**Comment by SEjoe** [comment]
sure > Fooman_Common 1.2.5 (stable)

**Comment by fooman** [comment]
I am afraid that's the extend of ideas to try from afar. I'd suggest making sure that all installed files have the correct permissions for the server to find and read them. We can take a closer look for you as part of our installation service available from our website.

**Comment by SEjoe** [comment]
np, thanks for responding
