### ISSUE TITLE
Issue with CE 1.9.1

### ISSUE THREAD

**Issue by pmainguet** [fooman/googleanalyticsplus#70]
Hi! Thanks for this great plugin. It worked OK on my website until I test on someone else computer, without clicking on the Authorize Cookies notice.

In this case, when I try to checkout, the login form doesn't show up and I have a "ga is not defined" error. The error is triggered by the Google Analytics function you used, but I was unable to understand why it can't recognize the function if cookies are not enabled.

Thanks for your feedback, as I have disabled your plugin for the moment

**Comment by fooman** [comment]
Usually if you don't accept cookies nothing of Magento should be able work as it relies on a session cookie for carts, logins, etc. (or it doesn't work properly). We might be able to wrap something around https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/template/fooman/googleanalyticsplus/ajax-tracking.phtml#L5 but again you shouldn't have been able to checkout in the first place.

**Comment by pmainguet** [comment]
OK, I look into that. Thanks!
