### ISSUE TITLE
array of product id's for configurable product

### ISSUE THREAD

**Issue by simonr44** [fooman/googleanalyticsplus#71]
We are using Dynamic Remarketing. When viewing a configurable product with several attached simple products, the Product ID of the configurable product is output as the ecomm_prodid. This does not relate to our feed and causes the tag to fail validation.

Ideally for us the ecomm_prodid should be set to a list of the attached simple products product IDs

Example:
Configurable product with ID 785, 5 simples attached with ID's 786,787,788,789,790

Current output: ecomm_prodid = 785,
Preferred output: ecomm_prodid = ["786","787","788","789","790"],

**Comment by phrench** [comment]
Another vote for this.

**Comment by chrisbfi** [comment]
Does ecomm_prodid accept multiple values in this way?

The Google documentation [here](https://support.google.com/adwords/answer/3103357) - look under the Retail section - states:

> ecomm_prodid: matches the feed attributes id, item_group_id, or display_ads_id

I suspect the answer may be to output the same value that's being shown as **ecomm_prodid** into your Google Shopping feed, into the **item_group_id** field.

**Comment by simonr44** [comment]
I'm sure when I first opened this issue Google were recommending we output multiple values, although the documentation is clearly not indicating this now.

The suggestion from chrisbfi has solved the problem for us, thank you for your time.
