### ISSUE TITLE
E-commerce tracking code missing from checkout success page

### ISSUE THREAD

**Issue by ecmiben** [fooman/googleanalyticsplus#72]
Hi Fooman,

The e-commerce tracking code is missing from our checkout success page.  Reproduced the problem in both Magento CE 1.7 and 1.9.  Tracked it down to the following file and line of code.

app/design/frontend/base/default/template/fooman/googleanalyticsplus/universal.phtml 

<?php if($this->isSuccessPage()):?> 

I worked around it by unconditionally including the e-commerce tracking code, but wrapping it in the following Javascript.

if (/checkout\/onepage\/success/.test(window.location.href)) {}

Am interested in a better fix.  Any ideas to troubleshoot further?

Thank you,

-Ben

**Comment by fooman** [comment]
Can you please post the html source of your success page without code change.

**Comment by ecmiben** [comment]
I can no longer reproduce this problem.  I believe it was originally broken by a theme, and silently fixed by an upgrade.

Thank you for the quick response,

-Ben
