### ISSUE TITLE
ecomm variables causing error.

### ISSUE THREAD

**Issue by Mel007** [fooman/googleanalyticsplus#82]
In the latest release the ecomm prodid is coming through which is great. But on a category page (with no product and no price), I think we have a missing   '',     before the closing brace. This is causing a js error.

var google_tag_params = {
                ecomm_prodid: '',
                ecomm_pagetype: 'category',
                                ecomm_totalvalue:             };

**Comment by fooman** [comment]
@Mel007 when you say latest release are you referring to the latest tagged version or latest commit? With this change here https://github.com/fooman/googleanalyticsplus/commit/a988c8a4fe754319cd17e1edf582ec748bce287d ecomm_totalvalue should not be displayed at all any more.

**Comment by Mel007** [comment]
not too sure.. I downloaded from https://github.com/fooman/googleanalyticsplus/archive/master.zip
to update the version I had installed on my site.

I looked at a988c8a and they've replaced ' ' with false ... but that would probably result in what I am seeing... i.e. the tag name is still being listed and only the value is being hidden. maybe Google mean the whole tag should be hidden? as missing quotes is causing an error. You can see this page as an example:
https://www.topfurnitureshop.co.uk/bedroom/bedroom-furniture/bedside-tables.html

**Comment by fooman** [comment]
I see - can you try changing this 
https://github.com/fooman/googleanalyticsplus/blob/master/app/design/frontend/base/default/template/fooman/googleanalyticsplus/remarketing.phtml#L23 to

    <?php if($pageValue !== false):?>

**Comment by Mel007** [comment]
Ok, that has removed the tag and therfore the error message, thanks!

I'm also looking at enhanced ecommerce in Google Analytics. I don't believe your extension tracks these tags does it?

specs are here https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

Thanks!
Mel

**Comment by fooman** [comment]
Hi Mel, thanks for confirming. No we do not support enhanced ecommerce.
