### ISSUE TITLE
missing ecomm_* on checkout page

### ISSUE THREAD

**Issue by magnored** [fooman/googleanalyticsplus#83]
On the payment page is not displayed the ecomm_ codes * like the image below:
![image](https://cloud.githubusercontent.com/assets/7586874/10975921/6d66f5e6-83d0-11e5-9367-1f6cf1d3ff05.png)

But in the shopping cart and product page is displayed correctly:
(cart example)
![image](https://cloud.githubusercontent.com/assets/7586874/10975974/bbaf8092-83d0-11e5-9a60-9f6c63d0afa3.png)

I'm using this checkout plugin:
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro

**Comment by fooman** [comment]
I don't understand what you mean by payment page. However the page types are detected here https://github.com/fooman/googleanalyticsplus/blob/master/app/code/community/Fooman/GoogleAnalyticsPlus/Block/Remarketing.php#L187 and this currently sounds okay to me. If this is a change introduced by your custom checkout extension you would need to adjust it there.
