### ISSUE TITLE
ga is not defined

### ISSUE THREAD

**Issue by justan0therdave** [fooman/googleanalyticsplus#84]
I get an error on my one page checkout if I enable Google Analytics + (Adwords seems to be fine) and it will not load.  Error on inspection is: ga is not defined

**Comment by fooman** [comment]
Does it happen when using the default theme and checkout? Any 404 errors of missing files when loading the page?

**Comment by justan0therdave** [comment]
http://www.googletagmanager.com/gtm.js?id=MY-CODE Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by fooman** [comment]
I'd suggest comparing the snippet Google gives you vs. what comes up in your store's html. It currently looks to me there is some disconnect between the two. We include the snippet wholesale so this seems to be unrelated to our code.

**Comment by abhilash-ussoftware** [comment]
Hi, Do you have any suggestion for this? I am also having same issue? Please help.

**Comment by justan0therdave** [comment]
This was due to some hardcoding in my magento installation that I wasn't aware of.

**Comment by abhilash-ussoftware** [comment]
Thank you. Do you remember what was exactly hard coded,because I am also having same issue. Appreciate your help on this.

**Comment by justan0therdave** [comment]
Mine was hardcoded in footer.phtml.  Have a look in the files in: app/design/frontend/yourstyle/default/template/page/html/

**Comment by abhilash-ussoftware** [comment]
Sure, thank you.

**Comment by abhilash-ussoftware** [comment]
In my case Google code was not added where ga is initialized. Thank you.
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5428281-1', 'auto');
  ga('send', 'pageview');

</script>
