### ISSUE TITLE
Tracking true referals instead of PSP payment providers in GUA

### ISSUE THREAD

**Issue by seansan** [fooman/googleanalyticsplus#85]
Hi, we are seeing a lot of bank traffic in GUA as the source of our revenue. This is not correct and they are not  incorrectly counted as the referer. Explained here: https://www.optimizesmart.com/tracking-true-referrals-in-google-analytics-when-using-paypal-and-other-payment-gateways/ and here http://blog.analytics-toolkit.com/2015/payment-gateway-referrer-exclusions-google-analytics/

There is a manual method in GUA to exclude domains. 

But can this possible be done in the extension?

**Comment by fooman** [comment]
Hi sensan none of the resources you linked to includes details on how one would do this without going through the Google interface (with one method self describing as being somewhat of a hack). If you are able to find official documentation on how this could be achieved from the javascript tracking we can take another look. Feel free to re-open if you can find official documentation on this.
