### ISSUE TITLE
Ajax One Page One Step Checkout

### ISSUE THREAD

**Issue by etsanov** [fooman/googleanalyticsplus#91]
Hi! 

We are using the following one page checkout solution:

https://www.magecheckout.com/

How are we supposed to set up the sales funnel? The checkout page does not change its URL. The shipping and payment methods are usually preselected but can also be changed via the checkout page through Ajax calls. The URL of the checkout page remains the same. How is the funnel created in this case?

Thank you in advance for your expertise and comments!

**Comment by fooman** [comment]
@etsanov you would only be able to set up a funnel that combines the checkout to the one page ie cart->checkout->success.

http://onestepcheckout.com has recently changed their code to send page views that are compatible with how our extension would send them.
