### ISSUE TITLE
Module "Fooman_GoogleAnalyticsPlus" requires module "Fooman_Common"

### ISSUE THREAD

**Issue by ammaar23** [fooman/googleanalyticsplus#92]
I've installed this extension but it is giving me the following error.
PHP Fatal error:  Uncaught exception 'Mage_Core_Exception' with message 'Module "Fooman_GoogleAnalyticsPlus" requires module "Fooman_Common".

Can you please help me with what could be the reason causing this issue.

**Comment by reinos** [comment]
Same issue here...

**Comment by jhoelzl** [comment]
I suppose, you just have to install the required extension: https://github.com/fooman/common

**Comment by fooman** [comment]
As mentioned the Common module needs to be installed as well.  Details for the various installation methods are outlined in the Readme.
