### ISSUE TITLE
Value should have two decimals

### ISSUE THREAD

**Issue by mikebranderhorst** [fooman/googleanalyticsplus#95]
https://github.com/fooman/googleanalyticsplus/blob/master/app/code/community/Fooman/GoogleAnalyticsPlus/Helper/Data.php#L52

`return $baseValue;`

should be:

`sprintf('%01.2f', $baseValue);`

https://github.com/fooman/googleanalyticsplus/blob/master/app/code/community/Fooman/GoogleAnalyticsPlus/Helper/Data.php#L56

`"%01.4f", Mage::app()->getStore()->roundPrice(`

should be:

`'%01.2f', Mage::app()->getStore()->roundPrice(`

Like the remarketing value:

https://github.com/fooman/googleanalyticsplus/blob/master/app/code/community/Fooman/GoogleAnalyticsPlus/Block/Remarketing.php#L119

https://github.com/fooman/googleanalyticsplus/blob/master/app/code/community/Fooman/GoogleAnalyticsPlus/Block/Remarketing.php#L129

**Comment by fooman** [comment]
Will be changed in 0.18.2
