### ISSUE TITLE
Wrong ecomm_totalvalue implementation

### ISSUE THREAD

**Issue by mikebranderhorst** [fooman/googleanalyticsplus#96]
The ecomm_totalvalue value is now an array, it should be the total value.

Example for multiple products:
ecomm_prodid: ['123', '456'], // sku
ecomm_pname: ['ABC','DEF'], // product name
ecomm_pvalue: [99, 19.99], // product value
ecomm_totalvalue: 118.99 // total value

The use of ecomm_pvalue is questionable. The parameter is not listed here: https://developers.google.com/adwords-remarketing-tag/parameters

**Comment by fooman** [comment]
Looks like Google has changed around their params yet again. Will take a look when we are able to devote some time to this extension.

**Comment by fooman** [comment]
Should be fixed in last release 0.18.3
