### ISSUE TITLE
Pageview issue on checkout after upgrading to v0.17.0

### ISSUE THREAD

**Issue by septoctobre** [fooman/googleanalyticsplus#98]
Hi,

I noticed a strange behavior after a v0.16.8 to v0.17.0 upgrade.
It seems that the "/checkout/onepage/opc-billing" pageview is sent before the "/checkout/onepage" pageview.

Does anyone else encounter this issue ?

Thanks

**Comment by jm111015** [comment]
Hello, 
It seems v0.17.0 doesn't track the e-commerce conversion.

Can I ask for help.

Thanks.

**Comment by septoctobre** [comment]
@jm111015 I just made a test and it works

**Comment by jm111015** [comment]
@septoctobre , did you manually put the ecommerce data layer code? Can I ask how you achieve on tracking the e-commerce conversion.

Thank you.

**Comment by septoctobre** [comment]
@jm111015 
There's no need to manually put the ecommerce code.

You need to :
- activate/configure e-commerce in analytics ([documentation](https://support.google.com/analytics/answer/1009612))
- activate/configure fooman analytics ([documentation](http://cdn.fooman.co.nz/media/custom/upload/UserManual-FoomanGoogleAnalyticsPlus.pdf))

**Comment by jm111015** [comment]
@septoctobere
Thank you for your favorable and quick response.
